# -*- mode: ruby -*-
# vi: set ft=ruby :
$script = <<-SCRIPT
echo I am provisioning
df -h >> /etc/vagrant_provisioned_at
sudo yum install -y vim
SCRIPT
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "base_vm"
  config.vm.network "public_network",
    use_dhcp_assigned_default_route: true,
    bridge: "wlp0s20f3"
  config.vm.provider "virtualbox" do |v|
  v.memory = 512
  v.cpus = 1
  config.vm.provision "shell", inline: $script
end
end
