# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "base_vm"
  config.vm.network "public_network",
    use_dhcp_assigned_default_route: true,
    bridge: "wlp0s20f3"
  config.vm.provider "virtualbox" do |v|
  v.memory = 512
  v.cpus = 1
end
end
