# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provision "shell",
    inline: "sudo yum -y install bash-completion vim epel-release htop && sudo yum -y update"
  config.vm.box = "centos/7"
  config.vm.define "base_vm"
  config.vm.hostname = "c7pc"
  config.vm.network "public_network",
    use_dhcp_assigned_default_route: true,
    bridge: "enp4s0",
    mac: "00163E010110"
  config.vm.provider "virtualbox" do |v|
  v.memory = 2048
  v.cpus = 2
end
end
